# Image Tensor

<img src="https://drive.google.com/uc?export=download&id=1ICXojPKmaPRqMB_xo4QoAhK1zEwMiN2F">

image는 가로, 세로로 픽셀들이 격자형태로 존재하는 데이터로 행렬로 취급할 수 있다.

<img src="https://drive.google.com/uc?export=download&id=1XaUTJkCIzY8NcM3LrqhnimnTfc2y3ZSa">

- 흑백이미지는 : H × W
- 컬러이미지는 : H × W × C
- 컬러이미지 + batch-size : N × H × W × C

# Correlation
image 데이터에 filter를 적용하는 연산으로 image와 kernel을 어떠한 방식으로 filtering할 것인가 하는 방법들 중 하나다.
<img src="https://drive.google.com/uc?export=download&id=1lSZG1wp8zxoZwYHEmdAzHZO5BIyQWWjJ">

Correlation 연산이 딥러닝에 적용이되면
<img src="https://drive.google.com/uc?export=download&id=1L_RYA5LZsmd1psRgMy44c_cGNLGh2Co5">
<img src="https://drive.google.com/uc?export=download&id=1Gf3qH7nbCeNc4L1iPQYuP1Ek96FNIkPX">

- filter가 weight matrix가 되면 bias가 추가된다.(Affine Transformation)
- Activation function도 추가될 수 있다.

# Dense Layer와 차이점
input matrix와 filter matrix에 flatten을 적용하면 row vector의 형태로 만들 수 있다.  
이 상태에서 correlation 연산을 진행해보면, 앞서 배운 Affine Transformation과 연산이 동일함을 볼 수 있다.  
여기서 Dense layer는 모든 입력이 각각의 뉴런에 input으로 반영되었으나, correlation 연산은 그렇지 않다.(뒤에서 window와 convolution을 보면 이해된다.)
<img src="https://drive.google.com/uc?export=download&id=1snwStb9dqnTg6gKjltudoGZXXFGajjZd">

# Windows
<img src="https://drive.google.com/uc?export=download&id=1v672frL3rOD_hI3jclGR7lxC7E7kAJli">
<img src="https://drive.google.com/uc?export=download&id=1m2Oo3A-h3tleHSki2YBT2UvvhbgK8Gq2">

- 정해진 규격의 window가 input 벡터를 이동하며 값을 가져오게 된다.  
- 2D 에서 i : height, j : width 를 가리킨다.

<img src="https://drive.google.com/uc?export=download&id=1YsW8dXtvmbKLsWN0EqwMBr3AJdBg4DPd">

- Window의 크기는 f × f
- window가 이미지의 n<sub>w</sub> - f 가 되어야 filter가 이미지의 마지막 width 픽셀까지 적용이 가능.
- height도 마찬가지.
- window에서 i + f, j + f로 적용하면, slicing이 end - 1까지 값을 가져오게 된다.
- 따라서 X[i + (f - 1), j + (f - 1)]


# Convolution Computation

### 1D convolutional
<img src="https://drive.google.com/uc?export=download&id=1S4uiPdEiDEJs75BeRhE1YZIwAMhY1Kie">

### 2D convolutional
<img src="https://drive.google.com/uc?export=download&id=1sWbSmhtTtxDypIyvV8s6ATrIeycqj2p9">

window와 correlation 연산이 모두 적용되는 형태로 convolution 연산이 이루어진다.
- 정해진 규격의 window가 input을 순회.
- window로 가져온 input의 부분 값과 Kernel(filter) 간의 correlation 연산 진행.
- kernel의 size는 window의 size와 동일하다.
- input을 모두 순회할 때까지 반복하고, 이들을 종합하여 output vector(matrix)를 만들어낸다.
- convolution layer를 통과하게 되면, input image size가 축소된다.

### 2D convolutional + Activation
<img src="https://drive.google.com/uc?export=download&id=1pLARvvjQopgge05NFzi2t-eRQhPFvbwZ">

<img src="https://drive.google.com/uc?export=download&id=1Sqh6yrWp_XJ5MtH-GsDwmP5VdKChIplK">

# RGB image
<img src="https://drive.google.com/uc?export=download&id=12Lz99A5LzkSTp8QP2PJe9iKQW3qM1O0m">

RGB image는 image matrix 3개가 하나의 데이터를 이루고 있다.
- X[:, :, 0] - R
- X[:, :, 1] - G
- X[:, :, 2] - B

<img src="https://drive.google.com/uc?export=download&id=1N9am48NhuRkB93Ld5qlPptgffuEpjH2W">
<img src="https://drive.google.com/uc?export=download&id=1IBpSFqeZHHQy6gtF_cMhEyvGuRUuWQbt">
<img src="https://drive.google.com/uc?export=download&id=1NMTeDBOWz-4pnhzfaz5lLIyH06Zt9pNy">

따라서 Window도 f × f 크기에 n<sub>c</sub>의 channel size를 가지게 된다.  
- 가로, 세로의 크기가 5인 경우
- Window : 5 × 5 × 3
- RGB 채널을 한 번에 훑어 보는 window.
- window의 크기와 동일하게 kernel size도 설정된다.




# Convolution layer Single filter
<img src="https://drive.google.com/uc?export=download&id=12eWibWc5c7ywPmA08IumkhXmnjTiVBLy">
<img src="https://drive.google.com/uc?export=download&id=1iHNvbfSRiNGKrlhMFHlGQbi3cx4vvHzg">

1개의 filter를 가진 Convolution layer.
f×f×3크기의 window가 input X를 이동하며 correlation + Activation function을 진행한다.  
따라서 스칼라인 결과값들로 구성된 output shape = H × W가 만들어지게 된다.

(1개의 뉴런을 가진 dense layer와 동일한 개념이라고 보면 된다.)


# Convolution layer multiple kernel
<img src="https://drive.google.com/uc?export=download&id=1iHNvbfSRiNGKrlhMFHlGQbi3cx4vvHzg">

1개의 convolution layer가 여러 개의 filter를 가지게 되는 경우,
- filter의 shape은 모두 동일.
- 단, 각각의 filter 내부 weight 값은 모두 다르다.
- 각각의 filter를 거쳐서 얻은 output matrix를 모두 더함.

<img src="https://drive.google.com/uc?export=download&id=1C0sqxnwFYnYRgLp88rgT4szZ6uVSXz75">

- X가 l<sub>i</sub>개의 feature를 가지고 있다.
- 첫번째 conv-layer는 f×f×3 에 l<sub>i</sub>개의 weight를 가지고 있으며 l<sub>1</sub>개의 filter를 가지고 있다.
- 이를 통과하고 얻은 matrix의 형태는 H × W × l<sub>1</sub>
- 위와 동일하게 다음 conv-layer를 통과.

<img src="https://drive.google.com/uc?export=download&id=18eefv6vyWxaum3BcdJF2aWhsJ9iIrmd3">

<img src="https://drive.google.com/uc?export=download&id=1uY4RVzAg7iJ_za9DBUNjLZgwm0fBBmKj">

In [2]:
## Gray Scale image

import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 1
n_filter = 1 ## num filter
k_size = 3 ## kernel size

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)
y = conv(images)
W, B = conv.get_weights()

print(images.shape)
print(W.shape) ## H, W, C, N_filter(뉴런의 수)
print(B.shape)
print(y.shape) ## 28 - 3 + 1

(1, 28, 28, 1)
(3, 3, 1, 1)
(1,)
(1, 26, 26, 1)


In [3]:
## RGB Scale image

import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 3
n_filter = 1 ## num filter
k_size = 3 ## kernel size

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)
y = conv(images)
W, B = conv.get_weights()

print(images.shape)
print(W.shape) ## H, W, C, N_filter(뉴런의 수)
print(B.shape)
print(y.shape) ## 28 - 3 + 1

(1, 28, 28, 3)
(3, 3, 3, 1)
(1,)
(1, 26, 26, 1)


In [11]:
## numpy manual
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1 ## num filter
k_size = 3 ## kernel size

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)
y = conv(images)
W, B = conv.get_weights()

### manual
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
        # print(i, j)
        window = images[i : i+k_size, j : j+k_size]
        y_man[i, j] = np.sum(window * W) + B

print(images.shape)
print(W.shape)
print(B.shape)

print(f"y tensorflow : {y.shape} \n {y.numpy().squeeze()}")
print(f"y man : {y_man.shape} \n {y_man}")

(5, 5)
(3, 3)
(1,)
y tensorflow : (1, 3, 3, 1) 
 [[-3.44581902e-04 -2.38220841e-02 -3.71550918e-01]
 [-3.21483195e-01 -4.65770662e-01 -3.98087680e-01]
 [-6.36238605e-02 -1.12412035e-01 -1.85237736e-01]]
y man : (3, 3) 
 [[-3.44574451e-04 -2.38220841e-02 -3.71550918e-01]
 [-3.21483165e-01 -4.65770602e-01 -3.98087740e-01]
 [-6.36238754e-02 -1.12412021e-01 -1.85237736e-01]]


In [46]:
## numpy manual color image
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1 ## num filter
k_size = 3 ## kernel size

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)
y = conv(images)
W, B = conv.get_weights()

### manual
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
        # print(i, j)
        window = images[i : i+k_size, j : j+k_size, :]
        y_man[i, j] = np.sum(window * W) + B

print(images.shape)
print(W.shape)
print(B.shape)

print(f"y tensorflow : {y.shape} \n {y.numpy().squeeze()}")
print(f"y man : {y_man.shape} \n {y_man}")

(5, 5, 3)
(3, 3, 3)
(1,)
y tensorflow : (1, 3, 3, 1) 
 [[ 0.82929844 -0.01844898  0.672023  ]
 [ 0.512003    0.00407238  0.47438905]
 [-0.10338495  0.39780995  0.6445194 ]]
y man : (3, 3) 
 [[ 0.82929832 -0.01844907  0.67202294]
 [ 0.51200294  0.0040725   0.47438905]
 [-0.10338486  0.39780998  0.64451939]]


In [21]:
## convolution multiple kernels
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

batch_size, height, width, channel = 10, 28, 28, 3
n_filter = 5
k_size = 3

image = tf.random.uniform(minval=0, maxval = 1, shape=(batch_size, height, width, channel))
conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(image)

W, B = conv.get_weights()

print(image.shape)
print(W.shape, B.shape)
print(Y.shape)

(10, 28, 28, 3)
(3, 3, 3, 5) (5,)
(10, 26, 26, 5)


<img src="https://drive.google.com/uc?export=download&id=16hs-fKc4mKtax2zAqPEf8_q9oIM8fZHK">

In [27]:
## conv layer output의 shape를 정리(N, H, W)하는 방법.
import numpy as np

images = np.random.randint(low=0, high=10, size=(2, 3, 4))
for c in range(4):
    print(images[:, :, c])

images = np.transpose(images, (2, 0, 1))
print(images.shape)

[[4 2 3]
 [1 9 3]]
[[7 7 8]
 [4 1 7]]
[[3 1 1]
 [9 5 6]]
[[1 4 6]
 [7 7 3]]
(4, 2, 3)


In [43]:
## multiple kernel conv layer + manual

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

batch_size, height, width, channel = 1, 5, 5, 3
n_filter = 5
k_size = 3

image = tf.random.uniform(minval=0, maxval = 1, shape=(batch_size, height, width, channel))

## Tensorflow
conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(image)
Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print(f"Y tensorflow : {Y.shape} \n {Y} \n")

W, B = conv.get_weights()

## manual
image = image.numpy().squeeze()
print(image.shape)
print(W.shape, B.shape) ## height, width ,channel, kernel

Y_man = np.zeros(shape=(height - k_size + 1, width - k_size + 1, n_filter))
for c in range(n_filter):
    c_W = W[:, :, :, c] ## 3 by 3
    c_b = B[c] ## 1

    for h in range(height - n_filter + 1):
        for w in range(width - n_filter + 1):
            window = image[h:h+k_size, w:w+k_size, :]
            conv = np.sum(window * c_W) + c_b

            Y_man[h, w, c] = conv

Y_man = np.transpose(Y_man, (2, 0, 1))
print(f"Y manual : {Y_man.shape}")    

Y tensorflow : (5, 3, 3) 
 [[[-0.42933172 -0.5158518  -0.6199455 ]
  [-0.12647565 -0.29189658 -0.28027344]
  [-0.4321921  -0.71040654 -0.33408332]]

 [[-0.16057464  0.23892467 -0.09257627]
  [ 0.0428706  -0.19386734 -0.3895949 ]
  [-0.27564543 -0.3258912   0.27089885]]

 [[ 0.39249593  0.00245518 -0.00968595]
  [ 0.12194953  0.56839156  0.27787998]
  [ 0.68368     0.68982077  0.37812725]]

 [[ 0.7401816   0.7850511   0.36055082]
  [ 0.83511335  0.3930271   0.35861918]
  [ 0.6003498   0.20013998  0.1708646 ]]

 [[ 0.277403    0.51585066  0.7293358 ]
  [ 0.7140047   0.41943935 -0.10798562]
  [ 0.384962    0.1025049   0.3497496 ]]] 

(5, 5, 3)
(3, 3, 3, 5) (5,)
Y manual : (5, 3, 3)


In [45]:
## multiple kernel conv layer with activation func.

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

batch_size, height, width, channel = 1, 5, 5, 3
n_filter = 5
k_size = 3

image = tf.random.uniform(minval=0, maxval = 1, shape=(batch_size, height, width, channel))

## Tensorflow
conv = Conv2D(filters=n_filter, kernel_size=k_size, activation="sigmoid")
Y = conv(image)
Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print(f"Y tensorflow : {Y.shape} \n {Y} \n")

W, B = conv.get_weights()

## manual
image = image.numpy().squeeze()
print(image.shape)
print(W.shape, B.shape) ## height, width ,channel, kernel

Y_man = np.zeros(shape=(height - k_size + 1, width - k_size + 1, n_filter))
for c in range(n_filter):
    c_W = W[:, :, :, c] ## 3 by 3
    c_b = B[c] ## 1

    for h in range(height - n_filter + 1):
        for w in range(width - n_filter + 1):
            window = image[h:h+k_size, w:w+k_size, :]
            conv = np.sum(window * c_W) + c_b

            Y_man[h, w, c] = conv

Y_man = np.transpose(Y_man, (2, 0, 1))
print(f"Y manual : {Y_man.shape}")    

Y tensorflow : (5, 3, 3) 
 [[[0.65439355 0.63572997 0.63958544]
  [0.6601203  0.6343901  0.5939627 ]
  [0.66795987 0.6899615  0.64574033]]

 [[0.30873513 0.29040682 0.23424667]
  [0.32518047 0.3125997  0.39053205]
  [0.28720295 0.27480793 0.27775887]]

 [[0.44636437 0.55486476 0.41662878]
  [0.45851663 0.3183123  0.37474   ]
  [0.45333079 0.5621858  0.37323558]]

 [[0.6593952  0.7342711  0.71645665]
  [0.7017179  0.65005666 0.76184636]
  [0.7330101  0.6818343  0.7809943 ]]

 [[0.43423197 0.5892751  0.43577167]
  [0.52228576 0.48771918 0.34356016]
  [0.49372223 0.41652912 0.50684434]]] 

(5, 5, 3)
(3, 3, 3, 5) (5,)
Y manual : (5, 3, 3)


In [55]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.models import Sequential

n_neurons = [10, 20, 30] ## num kernels
kernel_size = 3

model = Sequential()
model.add(Conv2D(filters=n_neurons[0], kernel_size=kernel_size, activation="relu"))
model.add(Conv2D(filters=n_neurons[1], kernel_size=kernel_size, activation="relu"))
model.add(Conv2D(filters=n_neurons[2], kernel_size=kernel_size, activation="relu"))

x = tf.random.normal(shape=(32, 28, 28, 3))
predictions = model(x)

print(f"Input : {x.shape}")
print(f"Output : {predictions.shape}")

for layer in model.layers:
    W, B = layer.get_weights()
    print(W.shape, B.shape)

print("==================")
trainable_variables = model.trainable_variables
for train_var in trainable_variables:
    print(train_var.shape)

Input : (32, 28, 28, 3)
Output : (32, 22, 22, 30)
(3, 3, 3, 10) (10,)
(3, 3, 10, 20) (20,)
(3, 3, 20, 30) (30,)
(3, 3, 3, 10)
(10,)
(3, 3, 10, 20)
(20,)
(3, 3, 20, 30)
(30,)


<img src="https://drive.google.com/uc?export=download&id=1-WsqF4J4CIDSgaZooBjnx-s3hP3Yu8Db">

In [61]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D

n_neurons = [10, 20, 30] ## num kernels

class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        global n_neurons

        self.conv_layers = []
        for n_neuron in n_neurons:
            self.conv_layers.append(Conv2D(filters=n_neuron, kernel_size=kernel_size, activation="relu"))

    def call(self, x):
        print("input : ", x.shape)

        print("===== conv layers =====")
        for conv_layer in self.conv_layers:
            x = conv_layer(x)
            W, B = conv_layer.get_weights()
            print(W.shape, B.shape)
            print(f"{x.shape} \n")

        return x

model = TestModel()
x = tf.random.normal(shape=(32, 28, 28, 3))
predictions = model(x)

input :  (32, 28, 28, 3)
===== conv layers =====
(3, 3, 3, 10) (10,)
(32, 26, 26, 10) 

(3, 3, 10, 20) (20,)
(32, 24, 24, 20) 

(3, 3, 20, 30) (30,)
(32, 22, 22, 30) 



In [63]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D

n_neurons = [10, 20, 30] ## num kernels

class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        global n_neurons

        self.conv1 = Conv2D(filters=n_neurons[0], kernel_size=3, activation="relu")
        self.conv2 = Conv2D(filters=n_neurons[1], kernel_size=3, activation="relu")
        self.conv3 = Conv2D(filters=n_neurons[2], kernel_size=3, activation="relu")

    def call(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)

        return x

model = TestModel()
x = tf.random.normal(shape=(32, 28, 28, 3))
predictions = model(x)