In [1]:
import numpy as np

# indexing과 slicing
indexing을 사용하면 항상 rank(차원)가 감소한다. 반면 slicing은 차원이 유지된다.

In [8]:
b = np.arange(1, 13)
print(b)
print(b.shape, b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,) 1


In [9]:
indexing = b[1]
slicing = b[1 : 2]

print(indexing, indexing.shape, indexing.ndim) ## 1차원 vector에서 scalar 값으로 차원이 감소.
print(slicing, slicing.shape, slicing.ndim) ## 1차원 vector 유지.

2 () 0
[2] (1,) 1


In [10]:
b = b.reshape(3, 4) ## 2차원 행렬로 reshape
print(b)
print(b.shape, b.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4) 2


In [11]:
row_r1 = b[1, :] ## 첫번째 row를 선택(indexing), col은 전체 다 가져온다.
row_r2 = b[1:2, :] ## 첫번째 row를 선택(slicing), col은 전체.

## 결과는 동일하지만
print(row_r1, row_r1.shape, row_r1.ndim) ## 2차원 행렬 -> 1차원 벡터
print(row_r2, row_r2.shape, row_r2.ndim) ## 2차원 행렬 -> 2차원 행렬

[5 6 7 8] (4,) 1
[[5 6 7 8]] (1, 4) 2


In [12]:
c = np.arange(24).reshape(2, 3, 4) ## 3 by 4 matrix가 2개.
print(c)
print(c.shape, c.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4) 3


In [20]:
print(c[0])
print(c[0:1])
print(c[1:2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [14]:
print(c[:, :, :1])
print(c[..., :1]) ## ... -> 앞에 값을 전부 가져온다.

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]
[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]


# Boolean Indexing

In [21]:
c = np.arange(24).reshape(2, 3, 4) ## 3 by 4 matrix가 2개.
print(c)
print(c.shape, c.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4) 3


In [22]:
bool_idx = (c > 10)
print(bool_idx)

[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [23]:
## 위에서 만든 boolean mask를 array에 indexing을 하게 되면 차원을 무시하고 True인 값을 가져오게 된다.
print(c[bool_idx])

[11 12 13 14 15 16 17 18 19 20 21 22 23]


In [27]:
## 값을 대입하게 되면 array에서 값만 변경된다. rank를 유지함.
c[c > 10] = -1
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 -1]]

 [[-1 -1 -1 -1]
  [-1 -1 -1 -1]
  [-1 -1 -1 -1]]]


# Fancy indexing

In [28]:
d = np.arange(8).reshape(8, -1) ## 원소의 수와 reshape의 첫번째 값을 계산해서 두번째값 -1이 알아서 채워진다.
print(d, d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


In [29]:
test = np.arange(8).reshape(4, -1) ## 8개의 원소를 4개의 row에 넣으니, col=2
print(test, test.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]] (4, 2)


In [31]:
## np.hstack : horizontal(수평선) 방향으로 stack을 쌓는다.
d_hstack = np.hstack((d, d, d, d))
print(d_hstack, d_hstack.shape)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]] (8, 4)


In [33]:
print(d_hstack[[3, 5, 1, 0]]) ## fancy indexing

[[3 3 3 3]
 [5 5 5 5]
 [1 1 1 1]
 [0 0 0 0]]


In [34]:
e = np.arange(32).reshape(8, 4)
print(e, e.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] (8, 4)


In [35]:
print(e[[1, 5, 7, 2]])

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]


In [36]:
print(e[[1, 5, 7, 2], [0, 3, 1, 2]]) ## row, col의 index가 된다.

[ 4 23 29 10]


In [39]:
print(e[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


#Transpose

In [40]:
f = np.arange(16).reshape(2, 2, 4)
print(f, f.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [42]:
print(f.transpose(2, 1, 0))
print(f.transpose(2, 1, 0).shape)

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]
(4, 2, 2)


In [43]:
print(f.swapaxes(0, 1)) ## swapaxes는 두 개의 축을 골라서 바꾼다. transpose가 더 general함.

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
