In [1]:
import numpy as np

# np.array()

In [2]:
a = np.array([1, 2, 3]) ## 배열을 생성.
print(a)
print(type(a))
print(a.ndim) ## 차원의 수. 배열의 랭크.
print(a.shape)
print(a.dtype)

[1 2 3]
<class 'numpy.ndarray'>
1
(3,)
int64


# np.asarray()
asarray는 array와 마찬가지로 입력된 데이터를 배열로 만들지만, 입력이 이미 dtype 및 order와 일치하는 ndarray인 경우 복사가 수행되지 않고 같은 메모리를 참조한다.  
따라서 어느 한쪽에서 값을 변경하면 두 배열 모두 값이 변경된다.

In [3]:
b = np.asarray(a)
print(b)

[1 2 3]


In [4]:
b[0] = 9
print(a)
print(b)

[9 2 3]
[9 2 3]


In [5]:
a[1] = 10
print(a)
print(b)

[ 9 10  3]
[ 9 10  3]


In [6]:
c = np.array(a)
c[0] = 1
print(a)
print(b)
print(c)

[ 9 10  3]
[ 9 10  3]
[ 1 10  3]


# np.zeros(), np.ones(), np.full(), np.empty()

- np.zeros : 입력된 shape의 matrix를 생성하는데 원소가 모두 0인 matrix이다.
- np.ones : zeros와 동일한 기능을 하지만, 행렬의 원소가 모두 1로 채워진다.
- np.full : zeros와 동일하지만, 두번째 인수로 전달된 값이 모든 원소로 적용된 matrix를 생성한다.
- np.empty : 입력된 shape의 형상의 matrix를 생성. random값으로 원소가 채워진다.

In [7]:
a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
b = np.ones((5, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
c = np.full((2, 3), 4)
print(c)

[[4 4 4]
 [4 4 4]]


## zeros_like, ones_like, full_like, empty_like

위에서 다룬 zeros, ones, full, empty와 기능적으로 동일하지만 입력된 array의 shape과 동일하게, 0 또는 1 또는 n 또는 random값으로 채워진 행렬을 만든다.

In [11]:
e = np.zeros_like(a)
f = np.ones_like(a)
g = np.full_like(a, 2)
h = np.empty_like(a)

print(e)
print(f)
print(g)
print(h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[1.94073413e-316 0.00000000e+000 9.82696570e-321 1.94014362e-316]
 [6.90771717e-310 1.94014757e-316 6.90771717e-310 6.90771717e-310]
 [0.00000000e+000 4.94065646e-324 2.12199579e-314 5.43472210e-323]]


# np.eye, np.identity

np.eye는 row와 col의 값을 입력 받고, 시작 위치도 설정할 수 있다.  
np.identity는 항상 정사각행렬을 만든다.

In [14]:
i = np.eye(3, 2)
j = np.identity(3)

print(i)
print(j)

[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# np.arange()

range()함수처럼 start ~ (end-1) 까지의 값을 가지는 array를 생성.

In [16]:
a = np.arange(1, 11)
print(a)

b = np.arange(10, 0, -1)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


# np.random.rand

uniform distribution. 0 ~ 1사이 값을 동일한 확률로 추출한다.

In [17]:
a = np.random.rand(2, 2)
print(a)

[[0.87780028 0.1950869 ]
 [0.01417751 0.7995813 ]]


# np.random.randn

normal distribution. 표준 정규분포(평균이 0이고 표준편차가 1)를 따라 숫자를 추출.

In [18]:
a = np.random.randn(2, 2)
print(a)

[[ 0.10467383  0.08983945]
 [ 0.84417987 -0.4686875 ]]


# astype
array의 dtype을 변경하고 싶을 때 사용.

In [19]:
a = np.array([10, 20, 30], dtype=np.int32)
b = a.astype(np.float32)

print(a.dtype, b.dtype)

int32 float32
