# Tensor

tensor는 multi-dimensional array를 나타내는 말로(vector와 matrix를 포함), Tensorflow와 Pytorch의 기본 data type이다.

In [1]:
import tensorflow as tf

In [2]:
c = tf.constant([3, 3], dtype=tf.float32) ## 상수형 텐서
print(c)

tf.Tensor([3. 3.], shape=(2,), dtype=float32)


In [4]:
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
print(c)
print(type(c))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


#Variable

In [5]:
## 상수형 텐서는 값을 변경할 수 없음 - immutable
const_tensor = tf.zeros((3, 3))
print(const_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [6]:
const_tensor[0, 0] = 9

TypeError: ignored

In [8]:
## 변수형 텐서는 weight, bias 같은 파라미터들을 업데이트 할 수 있도록 값을 변경할 수 있다.

var_tensor = tf.Variable(tf.zeros((3, 3)))
print(var_tensor)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>


In [10]:
var_tensor[0, 0].assign(9) ## 새로운 값을 할당할 때는 assign을 사용.
print(var_tensor)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[9., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>


In [11]:
initial_value = tf.random.normal(shape=(2, 2))
weight = tf.Variable(initial_value)
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.27057886, -0.09846831],
       [-0.20295724,  0.19483928]], dtype=float32)>


In [14]:
weight = tf.Variable(tf.random_normal_initializer(stddev=1.)(shape=(2, 2)))
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.0536194 , -0.5681296 ],
       [-0.05801524, -1.3948624 ]], dtype=float32)>


In [15]:
new_value = tf.random.normal(shape=(2, 2))
print(new_value)

weight.assign(new_value)
print(weight)

tf.Tensor(
[[-0.3576704  -0.89492965]
 [ 2.0982134   0.3462078 ]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.3576704 , -0.89492965],
       [ 2.0982134 ,  0.3462078 ]], dtype=float32)>


In [16]:
new_value = tf.random.normal(shape=(2, 2))
print(new_value)

weight.assign_add(new_value) ## 기존값과 신규값을 더하고 할당.
print(weight)

tf.Tensor(
[[ 0.90163857  0.8746441 ]
 [-1.0262305   1.0492218 ]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.5439682 , -0.02028555],
       [ 1.071983  ,  1.3954296 ]], dtype=float32)>


In [17]:
## tf.reduce_sum np.sum과 동일하다.
z = tf.range(1, 11)
z = tf.reshape(z, (2, 5))
print(z)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


In [19]:
print(tf.reduce_sum(z))
print(tf.reduce_sum(z, axis=0))
print(tf.reduce_sum(z, axis=1))
print(tf.reduce_sum(z, axis=-1))

tf.Tensor(55, shape=(), dtype=int32)
tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)
