## 1.Affine Transform

In [ ]:
## 1개 데이터, 1개의 값에 대한 Affine Transform.
import tensorflow as tf

x = tf.constant([[10.]]) ## vector([10.])가 아니라 matrix([[10.]]) 형태임에 유의할 것. shape = (1, 1)

dense = tf.keras.layers.Dense(units=1, activation="linear") ## affine function

y = dense(x) ## output. forward propagation + parameter initialization(x값이 입력되는 시점에 weight, bias가 초기화 된다.)

W, B = dense.get_weights()

## Manual
y_manual = tf.linalg.matmul(x, W) + B

## print reuslt
print(f"x : {x.shape}, {x.numpy()}")
print(f"W : {W.shape}, {W}")
print(f"B : {B.shape}, {B}")
print(f"y : {y.shape}, {y.numpy()}")
print(f"y manual : {y_manual.shape}, {y_manual}")

In [ ]:
## weight, bias Initializer

import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.constant([[1., 4., 7.]]) ## (1, 3) row vector

dense = Dense(units=1, activation="linear") ## (3, 1) column vector
y = dense(x) ## 1 by 1

W, b = dense.get_weights()
print(f"input : {x.shape} \n {x} \n")
print(f"Weight : {W.shape} \n {W} \n")
print(f"bias : {b.shape} \n {b} \n")
print(f"output : {y.shape} \n {y}")

In [ ]:
## 한 개의 row vector data. 10개의 feature.
x = tf.random.uniform(shape=(1, 10), minval=0, maxval=10)

dense = tf.keras.layers.Dense(units=1)
y = dense(x)
W, B = dense.get_weights()

y_manual = tf.linalg.matmul(x, W) + B

## print reuslt
print(f"x : {x.shape} \n {x.numpy()}") ## row vector
print(f"W : {W.shape} \n {W}") ## column vector
print(f"B : {B.shape} \n {B}")
print(f"y : {y.shape} \n {y.numpy()}")
print(f"y manual : {y_manual.shape}, {y_manual}")

## 2.Mini-batch

In [ ]:
## Affine Transform + Activation function with Mini-batch
N, n_feature = 3, 5
x = tf.random.normal(shape=(N, n_feature))

dense = tf.keras.layers.Dense(units=1, activation="sigmoid")
y = dense(x)

## Mini-batch size는 weight, bias에 영향을 끼치지 않는다!!!
W, B = dense.get_weights()

print(f"x : {x.shape} \n {x.numpy()}")
print(f"W : {W.shape} \n {W}")
print(f"B : {B.shape} \n {B}")
print(f"y : {y.shape} \n {y.numpy()}")

y_man = tf.linalg.matmul(x, W) + B
y_man = 1 / (1 + tf.math.exp(-y_man))

print(f"y tensorflow: {y.shape} \n {y.numpy()} \n")
print(f"y manual : {y_man.shape} \n{y_man.numpy()}")

# 3.Layer

In [ ]:
## Mini-batch input과 multiple neurons

import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant, RandomUniform

# w, b = tf.constant(2.), tf.constant(1.)
# w_init, b_init = Constant(w), Constant(b)
w_init, b_init = RandomUniform(minval=0, maxval=3), RandomUniform(minval=0, maxval=3)

X = tf.random.uniform(shape=(3, 3), minval=0, maxval=3, dtype=tf.int32)
dense = tf.keras.layers.Dense(units=4, 
                              activation="linear", 
                              kernel_initializer=w_init, 
                              bias_initializer=b_init)
Y = dense(X)

W, B = dense.get_weights() ## Bias도 뉴런의 수만큼 생성된다.

print(f"Input : {X.shape} \n {X.numpy()} \n")
print(f"Weight : {W.shape} \n {W} \n")
print(f"Bias : {B.shape} \n {B} \n")
print(f"Output : {Y.shape} \n {Y.numpy()}")

Input : (3, 3) 
 [[0 2 0]
 [0 1 0]
 [1 2 0]] 

Weight : (3, 4) 
 [[2.5851223  2.7393     0.8288884  0.766943  ]
 [1.8277302  0.34176064 0.86527026 2.2301023 ]
 [0.7015815  2.6197593  2.0963602  0.47183955]] 

Bias : (4,) 
 [2.8081748  0.59560454 1.3720304  1.5374794 ] 

Output : (3, 4) 
 [[6.4636354 1.2791258 3.102571  5.997684 ]
 [4.6359053 0.9373652 2.2373006 3.7675817]
 [9.048758  4.018426  3.9314594 6.764627 ]]


<img src="https://drive.google.com/uc?export=download&id=1VV73NLtIyYKUMzybk8bzJm3Rk1Bvn-jH">

<img src="https://drive.google.com/uc?export=download&id=1BlokXqSS2wGRik0bUv5v6GqWf4TqozXs">

연산 과정에 대해서 확실히 파악할 것.

In [ ]:
## Manual
import numpy as np
import tensorflow as tf

N, n_feature = 4, 5
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = tf.keras.layers.Dense(units=n_neuron, activation="sigmoid")
Y_tf = dense(X)

W, B = dense.get_weights()
print(f"Input : {X.shape} \n {X.numpy()} \n")
print(f"Weights : {W.shape} \n {W} \n")
print(f"Bias : {B.shape} \n {B} \n")

## calculate with matrix multiplication.
Z = tf.linalg.matmul(X, W) + B
Y_man_mat_mul = 1 / (1 + tf.math.exp(-Z))

## calculate with dot product.
Y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
  x = X[x_idx] ## row 단위로 접근.

  for neuron_idx in range(n_neuron):
    w, b = W[:, neuron_idx], B[neuron_idx] ## W[:, neuron_idx] column 단위로 접근.
    z = tf.reduce_sum(x * w) + b
    a = 1 / (1 + np.exp(-z))
    Y_man_vec[x_idx, neuron_idx] = a


print(f"Y tensorflow : {Y_tf.shape}, \n {Y_tf.numpy()} \n")
print(f"Y man mat_mul : {Y_man_mat_mul.shape}, \n {Y_man_mat_mul} \n")
print(f"Y man vec : {Y_man_vec.shape} \n {Y_man_vec} \n")

Input : (4, 5) 
 [[-0.65928537 -0.2480974   0.43367472  1.3678365  -0.1264271 ]
 [ 0.17658404 -0.09584612 -1.0973     -0.40444714  0.23457985]
 [-0.00544956  0.70416385  1.2003565  -1.6772876   0.97837424]
 [-0.01508621  0.75583154  1.0752207  -0.82584643 -0.1614769 ]] 

Weights : (5, 3) 
 [[-0.33535814 -0.76547253 -0.06815624]
 [ 0.33101016  0.7737184   0.52242225]
 [-0.16563344 -0.20004046  0.2815867 ]
 [-0.60301554  0.18159968 -0.19174463]
 [-0.26630932  0.00806332 -0.2891037 ]] 

Bias : (3,) 
 [0. 0. 0.] 

Y tensorflow : (4, 3), 
 [[0.32650948 0.6161726  0.45306733]
 [0.5676383  0.48465988 0.41063043]
 [0.68718123 0.50304246 0.67808956]
 [0.649799   0.5572443  0.7117081 ]] 

Y man mat_mul : (4, 3), 
 [[0.32650945 0.61617255 0.45306733]
 [0.5676383  0.4846599  0.41063043]
 [0.68718123 0.5030425  0.67808956]
 [0.649799   0.55724436 0.7117082 ]] 

Y man vec : (4, 3) 
 [[0.32650944 0.61617258 0.45306734]
 [0.56763829 0.48465988 0.41063043]
 [0.68718124 0.50304253 0.67808955]
 [0.649798

In [ ]:
## for문을 이용해서 layer들 사용하는 방법.

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_copy = tf.identity(X)

n_neurons = [3, 4, 5]
dense_layers = list()
for n_neuron in n_neurons:
  dense = tf.keras.layers.Dense(units=n_neuron, activation="sigmoid")
  dense_layers.append(dense)

print(f"Input : {X.shape}")

W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  w, b = dense.get_weights()

  W.append(w), B.append(b)

print(f"Y tf : \n {X.numpy()}")


for layer_idx in range(len(n_neurons)):
  w, b = W[layer_idx], B[layer_idx]
  X_copy = tf.linalg.matmul(X_copy, w) + b
  X_copy = 1 / (1 + tf.math.exp(-X_copy))

print(f"Y man : \n {X_copy.numpy()}")

#4.Sigmoid function

- weight, bias를 가지지 않음.
- output layer 직전까지의 모든 Layer가 Affine transform연산을 수행한다고 가정.
- Logit vector를 입력으로 받에 Probability로 출력.
- output layer는 뉴런이 1개(units=1)이며 activation = "sigmoid"로 설정.
- 뉴런이 1개이므로 output shape = 1 또는 (N, 1).

<img src="https://drive.google.com/uc?export=download&id=1z4DekNoW_ty2W80MIrkmrsoEAcDV_094">

In [ ]:
## Logistic Regression - Multi Variate
X = tf.random.normal(shape=(100, 5))
dense = tf.keras.layers.Dense(units=1, activation="sigmoid") ## Affine transform으로 1개의 logit 값을 구하고, sigmoid 반영.
Y = dense(X)

W, B = dense.get_weights()

print(f"Input : {X.shape} \n {X.numpy()[:3]} \n")
print(f"Weights : {W.shape} \n {W} \n")
print(f"Bias : {B.shape} \n {B} \n")
print(f"Output - Sigmoid : {Y.shape} \n {Y.numpy()[:3]}")

Input : (100, 5) 
 [[ 0.07885586  1.2067411   0.69738185  1.1121552   0.17453901]
 [-0.05307293  0.19124863 -1.4629031  -0.2412481  -0.24293447]
 [-0.07027663  0.7556984  -1.175209    0.39808595  0.9123695 ]] 

Weights : (5, 1) 
 [[ 0.7188616 ]
 [-0.02032185]
 [-0.46848083]
 [-0.30328465]
 [-0.66729736]] 

Bias : (1,) 
 [0.] 

Output - Sigmoid : (100, 1) 
 [[0.3211884 ]
 [0.7065278 ]
 [0.43908694]]


In [ ]:
## Binary Classifier with Dense Layers

X = tf.random.normal(shape=(100, 5))

model = tf.keras.models.Sequential()
# model.add(tf.keras.layers.Dense(units=10, activation="relu"))
# model.add(tf.keras.layers.Dense(units=5, activation="relu"))
# model.add(tf.keras.layers.Dense(units=1, activation="sigmoid")) ## Binary classifier

model.add(tf.keras.layers.Dense(units=10, activation="relu"))
model.add(tf.keras.layers.Dense(units=5, activation="relu"))
model.add(tf.keras.layers.Dense(units=1, activation="relu"))
model.add(tf.keras.layers.Activation("sigmoid"))

Y = model(X)
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_14 (Dense)            (100, 10)                 60        
                                                                 
 dense_15 (Dense)            (100, 5)                  55        
                                                                 
 dense_16 (Dense)            (100, 1)                  6         
                                                                 
 activation (Activation)     (100, 1)                  0         
                                                                 
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


# 5.Softmax function

- sigmoid와 마찬가지로 weight, bias를 가지지 않음.
- logit vector를 입력으로 받고, probability 형태로 바꿔준다.
- 이 때, vector의 각 원소는 각 class에 해당할 것이라는 확률값.
- probability vector의 총 합이 1이다.

<img src="https://drive.google.com/uc?export=download&id=1zLjDO-MjmbK74_I-zWXRScTr-I0MYecr">
<img src="https://drive.google.com/uc?export=download&id=11-c1XGGcunjid7hyI1VwuvWWl_cKkaQ4">

In [ ]:
## Softmax
logit = tf.random.uniform(shape=(5, 3), minval=-10, maxval=10)
softmax_value = tf.keras.layers.Activation("softmax")(logit)
softmax_sum = tf.reduce_sum(softmax_value, axis=1)

print(f"Logits : {logit.shape} \n {logit} \n")
print(f"Probabilities : {softmax_value.shape} \n {softmax_value} \n")
print(f"Sum of softmax values : \n {softmax_sum}")

Logits : (5, 3) 
 [[ 0.88398457 -3.945303   -7.8322077 ]
 [ 4.4274254   4.337284   -6.25705   ]
 [ 5.1670504   2.4240227  -7.380731  ]
 [-6.0878897   2.852028    4.2614384 ]
 [-5.7236433  -5.4685473  -4.6333027 ]] 

Probabilities : (5, 3) 
 [[9.9190980e-01 7.9275547e-03 1.6258407e-04]
 [5.2251381e-01 4.7747421e-01 1.1964355e-05]
 [9.3951517e-01 6.0481429e-02 3.3378881e-06]
 [2.5728361e-05 1.9632201e-01 8.0365229e-01]
 [1.8990204e-01 2.4508482e-01 5.6501317e-01]] 

Sum of softmax values : 
 [0.99999994 1.         0.99999994 1.         1.        ]


In [ ]:
## Softmax in Dense Layers
logit = tf.random.uniform(shape=(8, 5), minval=-10, maxval=10)
dense = tf.keras.layers.Dense(units=8, activation="softmax")
Y = dense(logit)
print(tf.reduce_sum(Y, axis=1))

In [ ]:
## Multiclass classifiers

class TestModel(tf.keras.models.Model):
    def __init__(self):
        super(TestModel, self).__init__()

        self.dense1 = tf.keras.layers.Dense(units=8, activation="relu")
        self.dense2 = tf.keras.layers.Dense(units=5, activation="relu")
        self.dense3 = tf.keras.layers.Dense(units=3, activation="softmax") ## 3 classes

    def call(self, x):
        print(f"X : {x.shape} \n {x.numpy()} \n")

        x = self.dense1(x)
        print(f"A1 : {x.shape} \n {x.numpy()} \n")

        x = self.dense2(x)
        print(f"A2 : {x.shape} \n {x.numpy()} \n")

        x = self.dense3(x)
        print(f"Y : {x.shape} \n {x.numpy()} \n")
        print(f"Sum of Y : {x.shape} \n {tf.reduce_sum(x, axis=1)}")

model = TestModel()
X = tf.random.uniform(shape=(8, 5), minval=-10, maxval=10)
Y = model(X)


#6.Loss functions

## 6-1.Mean Squared Erros

<img src="https://drive.google.com/uc?export=download&id=1YHlQlRMG3g3vHQgkKmq_PAxCBm4g6nSI">

- 입력 데이터 X는 l<sub>i</sub> 개의 feature를 가진 row vector가 N개 쌓여있는 Matrix.
- 학생1, 학생2, ... 들의 데이터가 batch size N만큼 존재.
- 데이터 row 각각에 대한 prediction value를 구하고, column vector $\hat{Y}$로 나타낸다.
- 정답값 y들이 vector로 묶인 column vector Y와 비교를 진행한다.
- batch-size N개에 대한 비교이므로 이에 대한 평균을 구함. Mean Squared Error.
- 평균을 구하는 이유는 N개의 y와 prediction 간의 차이를 평균 낸 것이 바로 loss 값.

In [ ]:
## Regression dataset 만들기

import tensorflow as tf

N, n_feature = 8, 5
X = tf.random.normal(mean=0, stddev=1, shape=(N, n_feature)) ## 8 by 5 matrix
target_weights = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32) ## 5 by 1 column
target_bias = tf.constant([10], dtype=tf.float32) ## 1 bias

print(X.shape, target_weights.shape, target_bias.shape)

Y = tf.reduce_sum(X * target_weights, axis=1) + target_bias
print(f"X : {X.shape} \n {X}")
print(f"Y : {Y.shape} \n {Y}")

## Mean Squared Error

loss_object = tf.keras.losses.MeanSquaredError()

batch_size = 32
predictions = tf.random.normal(shape=(batch_size, 1))
labels = tf.random.normal(shape=(batch_size, 1))

mse = loss_object(labels, predictions)
mse_man = tf.reduce_mean(tf.math.pow(labels - predictions, 2))
print(f"MSE tensorflow : {mse}")
print(f"MSE manual : {mse_man}")

In [ ]:
## Mean Squared Error with model

batch_size = 32
N, n_features = 100, 5
X = tf.random.normal(shape=(N, n_feature))
Y = tf.random.normal(shape=(N, 1))

dataset = tf.data.Dataset.from_tensor_slices((X, Y))
dataset = dataset.batch(batch_size)

dense = tf.keras.layers.Dense(units=1, activation="linear")
loss_object = tf.keras.losses.MeanSquaredError()

for x, y in dataset:
    predictions = dense(x)
    loss = loss_object(y, predictions)
    print(loss.numpy())

## 6-2.Binary Cross Entropy
<img src="https://drive.google.com/uc?export=download&id=1UElDXIkw1Y3HTgrariXNBheUCqvuV2A8">

- y = 1 인 경우, $(1-y)log(1-\hat{y}) = 0$이 된다. 따라서 $-log(\hat{y})$ 항만 남음.
- -log 함수는 입력이 1에 가까워질수록 출력이 0에 수렴하고, 입력이 0에 가까워질수록 출력이 무한히 발산한다.

- y = 0 인경우, $ylog(\hat{y})$ 항이 0이 된다. 따라서 $-log(1-\hat{y})$ 항만 남음.
- $-log(1-\hat{y})$ 함수는 입력값이 1에 가까워질수록 함수값은 무한히 발산. 입력값이 0에 가까워질수록 함수값은 0에 수렴한다.

In [ ]:
## Binary Classification
import tensorflow as tf

N, n_feature = 8, 5
target_weights = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
target_bias = tf.constant([10], dtype=tf.float32)

X = tf.random.normal(mean=0, stddev=1, shape=(N, n_feature))
print(f"X : {X.shape} \n {X}")
print(X.shape, target_weights.shape, target_bias.shape)

Y = tf.reduce_sum(X * target_weights, axis=1) + target_bias
print(f"reduce sum : {Y.shape} \n {Y.numpy()}")

Y = tf.cast(Y > 5, tf.int32) ## 5 이상이면 True, 미만이면 False.
print(f"Y : {Y.shape} \n {Y}")

In [ ]:
## Binary Cross Entropy
batch_size = 10
n_class = 2

predictions = tf.random.uniform(shape=(batch_size, 1), minval=0, maxval=1, dtype=tf.float32)
labels = tf.random.uniform(shape=(batch_size, 1), minval=0, maxval=n_class, dtype=tf.int32)

print(predictions) ## 10 by 1
print(labels) ## 10 by 1

loss_object = tf.keras.losses.BinaryCrossentropy()
loss = loss_object(labels, predictions)

labels = tf.cast(labels, tf.float32)
bce_man = -(labels * tf.math.log(predictions) + (1 - labels) * tf.math.log(1 - predictions))
bce_man = tf.reduce_mean(bce_man)

print(f"BCE : {loss}")
print(f"BCE man : {bce_man}")

In [ ]:
## Binary Cross Entropy with model

N, n_feature = 8, 5
target_weights = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32) ## 
target_bias = tf.constant([0], dtype=tf.float32)

X = tf.random.normal(mean=0, stddev=1, shape=(N, n_feature)) ## 8 by 5 matrix
Y = tf.reduce_sum(target_weights * X, axis=1) + target_bias ## affine transform 8 by 1
Y = tf.cast(Y > 5, tf.int32) ## 8 by 1

print(f"X : {X.shape} \n {X}")
print(f"Y : {Y.shape} \n {Y}")

dataset = tf.data.Dataset.from_tensor_slices((X, Y))
dataset = dataset.batch(batch_size)

dense = tf.keras.layers.Dense(units=1, activation="sigmoid")
loss_object = tf.keras.losses.BinaryCrossentropy()

for x, y in dataset:
    predictions = dense(x)
    print(f"predictions : {predictions.shape} \n {predictions}")
    loss = loss_object(y, predictions)
    print(loss.numpy())

##6-3. Categorical CrossEntropy

<img src="https://drive.google.com/uc?export=download&id=1s2i-DLyj7hyAJIYFXVQtKnqR18bVqQ4_">
<img src="https://drive.google.com/uc?export=download&id=1RAKAG5SNIqS7REHgqW3XhgNhtulubyBJ">

- index가 1부터 k까지 증가하면서 각각의 $-log{(\hat{y})}$ 값을 구함.
- 구한 loss 값을 다 더하면 한 개의 y vector와 prediction vector에 대한 차이. 오차.

<img src="https://drive.google.com/uc?export=download&id=1OWpDF4PlSOnyGfLBQYI3V8RB8FW9okp2">
- 전체 prediction matrix와 y matrix 간의 평균.

# 7.Convolutional layer

<img src="https://drive.google.com/uc?export=download&id=1L_RYA5LZsmd1psRgMy44c_cGNLGh2Co5">
<img src="https://drive.google.com/uc?export=download&id=1YsW8dXtvmbKLsWN0EqwMBr3AJdBg4DPd">
<img src="https://drive.google.com/uc?export=download&id=1sWbSmhtTtxDypIyvV8s6ATrIeycqj2p9">


- Dense layer처럼 모든 입력이 한 뉴런에 입력되는 형태가 아님.
- window라는 개념이 도입되어 input을 순차적으로 정해진 규격만큼 뽑아낸다.
- window 크기와 동일하게 kernel 규격이 만들어지고, window와 kernel간 correlation 연산을 수행한다.
- correlation은 window와 kernel간 element-wise product.
- element wise product 한 값을 모두 더하고, bias 값까지 더해주면 output matrix의 원소값이 된다.
- output matrix는 window가 순회하면서 만들어짐.

<img src="https://drive.google.com/uc?export=download&id=1Sqh6yrWp_XJ5MtH-GsDwmP5VdKChIplK">

In [ ]:
## Gray Scale image

import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 1
n_filter = 1 ## num filter
k_size = 3 ## kernel size

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)
y = conv(images)
W, B = conv.get_weights()

print(images.shape)
print(W.shape) ## H, W, C, N_filter(뉴런의 수)
print(B.shape)
print(y.shape) ## 28 - 3 + 1

In [ ]:
## numpy manual
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1 ## num filter
k_size = 3 ## kernel size

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)
y = conv(images)
W, B = conv.get_weights()

### manual
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
        # print(i, j)
        window = images[i : i+k_size, j : j+k_size]
        y_man[i, j] = np.sum(window * W) + B

print(images.shape)
print(W.shape)
print(B.shape)

print(f"y tensorflow : {y.shape} \n {y.numpy().squeeze()}")
print(f"y man : {y_man.shape} \n {y_man}")

##7-1.Color Image

<img src="https://drive.google.com/uc?export=download&id=1IBpSFqeZHHQy6gtF_cMhEyvGuRUuWQbt">
<img src="https://drive.google.com/uc?export=download&id=1NMTeDBOWz-4pnhzfaz5lLIyH06Zt9pNy">
<img src="https://drive.google.com/uc?export=download&id=1C0sqxnwFYnYRgLp88rgT4szZ6uVSXz75">
<img src="https://drive.google.com/uc?export=download&id=1uY4RVzAg7iJ_za9DBUNjLZgwm0fBBmKj">

- convolution layer의 filter의 수는 dense layer의 neuron의 수와 같다.(l<sub>i</sub>개의 뉴런(filter, kernel)을 배치했다.)
- 즉, output channel의 수가 filter의 수로 결정된다.

In [ ]:
## RGB Scale image

import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 3
n_filter = 1 ## num filter
k_size = 3 ## kernel size

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)
y = conv(images)
W, B = conv.get_weights()

print(images.shape)
print(W.shape) ## H, W, C, N_filter(뉴런의 수)
print(B.shape)
print(y.shape) ## 28 - 3 + 1

In [ ]:
## numpy manual color image
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1 ## num filter
k_size = 3 ## kernel size

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)
y = conv(images)
W, B = conv.get_weights()

### manual
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
        # print(i, j)
        window = images[i : i+k_size, j : j+k_size, :]
        y_man[i, j] = np.sum(window * W) + B

print(images.shape)
print(W.shape)
print(B.shape)

print(f"y tensorflow : {y.shape} \n {y.numpy().squeeze()}")
print(f"y man : {y_man.shape} \n {y_man}")

In [ ]:
## convolution multiple kernels
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

batch_size, height, width, channel = 10, 28, 28, 3
n_filter = 5
k_size = 3

image = tf.random.uniform(minval=0, maxval = 1, shape=(batch_size, height, width, channel))
conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(image)

W, B = conv.get_weights()

print(image.shape)
print(W.shape, B.shape)
print(Y.shape)

In [ ]:
## multiple kernel conv layer + manual

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

batch_size, height, width, channel = 1, 5, 5, 3
n_filter = 5
k_size = 3

image = tf.random.uniform(minval=0, maxval = 1, shape=(batch_size, height, width, channel))

## Tensorflow
conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(image)
Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print(f"Y tensorflow : {Y.shape} \n {Y} \n")

W, B = conv.get_weights()

## manual
image = image.numpy().squeeze()
print(image.shape)
print(W.shape, B.shape) ## height, width ,channel, kernel

Y_man = np.zeros(shape=(height - k_size + 1, width - k_size + 1, n_filter))
for c in range(n_filter):
    c_W = W[:, :, :, c] ## 3 by 3
    c_b = B[c] ## 1

    for h in range(height - n_filter + 1):
        for w in range(width - n_filter + 1):
            window = image[h:h+k_size, w:w+k_size, :]
            conv = np.sum(window * c_W) + c_b

            Y_man[h, w, c] = conv

Y_man = np.transpose(Y_man, (2, 0, 1))
print(f"Y manual : {Y_man.shape}")    

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D

n_neurons = [10, 20, 30] ## num kernels

class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        global n_neurons

        self.conv1 = Conv2D(filters=n_neurons[0], kernel_size=3, activation="relu")
        self.conv2 = Conv2D(filters=n_neurons[1], kernel_size=3, activation="relu")
        self.conv3 = Conv2D(filters=n_neurons[2], kernel_size=3, activation="relu")

    def call(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)

        return x

model = TestModel()
x = tf.random.normal(shape=(32, 28, 28, 3))
predictions = model(x)

# 8.Pooling layer

<img src="https://drive.google.com/uc?export=download&id=1N79DcioU7sm_zmOs4VF0Fxn5qoaZYJuA">
<img src="https://drive.google.com/uc?export=download&id=1yPfyaG9SDJOrFsubCIOb84tQYJshKjq7">
<img src="https://drive.google.com/uc?export=download&id=1eR10dcmFhHOWxHKy55II4B3YzOwXMVOz">

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D

batch_size, height, width, channel = 1, 5, 5, 1
pool_size, stride_size = 2, 1

x = tf.random.normal(shape=(batch_size, height, width, channel))
max_pool = MaxPooling2D(pool_size=pool_size, strides=stride_size)
max_pool_result = max_pool(x)

print(f"x : {x.shape} \n {x.numpy().squeeze()}")
print(f"max pool : {max_pool_result.shape} \n {max_pool_result.numpy().squeeze()}")

x = x.numpy().squeeze()
max_pool_man = np.zeros(shape=(height - pool_size + 1, width - pool_size + 1))

for i in range(height - pool_size + 1):
    for j in range(width - pool_size + 1):
        window = x[i : i + pool_size, j : j + pool_size]
        max_pool_man[i, j] = np.max(window)

print(f"max pool man : {max_pool_man.shape} \n {max_pool_man}")

In [ ]:
import math
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D

batch_size, height, width, channel = 1, 5, 5, 3
pool_size, stride_size = 2, 2

x = tf.random.normal(shape=(batch_size, height, width, channel))
print(f"x : {x.shape} \n {np.transpose(x.numpy().squeeze(), (2, 0, 1))} \n")

max_pool = MaxPooling2D(pool_size=pool_size, strides=stride_size)
max_pool_res = max_pool(x)
max_pool_res_t = np.transpose(max_pool_res.numpy().squeeze(), (2, 0, 1))
print(f"max pool res : {max_pool_res.shape} \n {max_pool_res_t} \n")

## manual
x = x.numpy().squeeze()
output_h = math.floor((height - pool_size) / stride_size + 1)
output_w = math.floor((width - pool_size) / stride_size + 1)

max_pool_man = np.zeros(shape=(output_h, output_w, channel))
print(max_pool_man.shape)

for c in range(channel):
    channel_wise_image = x[:, :, c]

    output_h_idx = 0
    for i in range(0, height - pool_size + 1 , stride_size):
        output_w_idx = 0
        for j in range(0, width - pool_size + 1, stride_size):
            window = channel_wise_image[i : i + pool_size, j : j + pool_size]
            max_pool_man[output_h_idx, output_w_idx, c] = np.max(window)

            output_w_idx += 1
        output_h_idx += 1

max_pool_man_t = np.transpose(max_pool_man, (2, 0, 1))
print(f"max pool man : {max_pool_man.shape} \n {max_pool_man_t} \n")

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import AveragePooling2D

batch_size, height, width, channel = 1, 5, 5, 1
pool_size, stride_size = 2, 1

x = tf.random.normal(shape=(batch_size, height, width, channel))
avg_pool = AveragePooling2D(pool_size=pool_size, strides=stride_size)
avg_pool_result = avg_pool(x)

print(f"x : {x.shape} \n {x.numpy().squeeze()}")
print(f"avg pool : {avg_pool_result.shape} \n {avg_pool_result.numpy().squeeze()}")

x = x.numpy().squeeze()
avg_pool_man = np.zeros(shape=(height - pool_size + 1, width - pool_size + 1))

for i in range(height - pool_size + 1):
    for j in range(width - pool_size + 1):
        window = x[i : i + pool_size, j : j + pool_size]
        avg_pool_man[i, j] = np.mean(window)

print(f"avg pool man : {avg_pool_man.shape} \n {avg_pool_man}")

# 9. Padding & Stride

<img src="https://drive.google.com/uc?export=download&id=1ybCQoMnO5p491sCX2DIt91gQshUNVVHg">
padding은 input matrix의 상하좌우에 임의의 값을 채워 넣는다.  
임의의 값이 0인 경우 Zero Padding이라 부른다. padding을 활용하게 되면, input matrix의 height, width가 축소되는 것을 방지할 수 있다.

<img src="https://drive.google.com/uc?export=download&id=1WuVTuFLhmBv-OwHrm0ODQnLQ2cdsxXa_">

stride는 window가 input matrix를 순회할때의 step을 뜻한다.  
1칸씩 이동하며 훑어보면 stride = 1이고, 2칸씩 이동(건너뜀)하며 보면 stride=2. 
따라서 stride를 적용하는 경우 input height, width가 작아질 수 있다.

<img src="https://drive.google.com/uc?export=download&id=1A7biAFCT6RSC3MfnxRJHiixHXMAYIc3P">

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import ZeroPadding2D

images = tf.random.normal(shape=(1, 3, 3, 3))
print(f"{images.shape}, \n {np.transpose(images.numpy().squeeze(), (2, 0, 1))} \n")

zero_padding = ZeroPadding2D(padding=1)
y = zero_padding(images)

print(f"{y.shape}, \n {np.transpose(y.numpy().squeeze(), (2, 0, 1))} \n")

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1, 28, 28, 3))
conv = Conv2D(filters=1, kernel_size=3, padding="same")
y = conv(images)

print(y.shape)

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1, 28, 28, 3))
conv = Conv2D(filters=1, kernel_size=3, padding="valid", strides=2)
y = conv(images)

print(y.shape)