##Layers
layer는 뉴런들의 집합이다.

1개의 뉴런은 lecture1에서 배운 Affine transformation과 Activation function의 조합으로 구성되어 있다.
<img src="https://drive.google.com/uc?export=download&id=1qHhyjBv6ntOdTPfeRjKSSzw1Q4Ap2cId">


<img src="https://drive.google.com/uc?export=download&id=1fmcvYvBK5a1bOk-x5u6JSSaFeqVSjqw2">

layer는 n개의 뉴런들이 모여서 이루는 뉴런 벡터 또는 뉴런들의 집합으로 생각할 수 있다.

이때 중요한 점은 각각의 뉴런들은 가지고 있는 parameter(weight, bias)들의 값이 모두 다르다.  
따라서 뉴런들이 동일한 입력을 받아도 각각의 뉴런들이 출력하는 output은 모두 제각각이다.

Activation Function은 parameter를 가지지 않기 때문에 Parametric Function이 아니다.

## Dense Layer
dense layer는 layer의 각 뉴런이 모든 input들을 받는 layer이다. 
<img src="https://drive.google.com/uc?export=download&id=1loCPF5u3GPVE5tPpgBgT2oRXJRDfCpGf">
<img src="https://drive.google.com/uc?export=download&id=16Qxnw6uUxQXhyL810inGTl0BvkhXofOA">


### 세부구조

<img src="https://drive.google.com/uc?export=download&id=1PW78TIKuy7nLfUh5wXfuzhsw3f-G6dKh">

{W<sub>k</sub><sub>j</sub>}<sup>[i]</sup>
- i : 몇번째 layer인가.
- j : layer 내에서 몇번째 뉴런인가.
- k : 뉴런 내에서 몇번째 weight인가.

각각의 뉴런들이 가지고 있는 weight, bias들을 각각 관리하기 귀찮으므로 행렬의 형태로 변환한다.<img src="https://drive.google.com/uc?export=download&id=1RLI6oVBv8W5BauEjecdSudUjgiz6N3Rp">



In [ ]:
import tensorflow as tf

N, n_feature = 1, 10 ## batch-size : 1, row vectors : 10 // (1, 10) input matrix
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = tf.keras.layers.Dense(units=n_neuron, activation="sigmoid") ## 3 neurons // (10 x 3) weight matrix
## Column wise == neuron
## 1열 : 1번 뉴런, 2열 : 2번 뉴런, 3열 : 3번 뉴런

Y = dense(X)
W, B = dense.get_weights()

print(f"X : {X.shape} \n {X.numpy()} \n")
print(f"W : {W.shape} \n {W} \n")
print(f"B : {B.shape} \n {B} \n")
print(f"Y : {Y.shape} \n {Y.numpy()} \n")

X : (1, 10) 
 [[-0.24915768 -0.01650841  0.05331842 -1.1055087  -1.0772789  -2.560363
  -0.4165717   0.7165221   0.8822942  -0.8384255 ]] 

W : (10, 3) 
 [[ 0.5867919  -0.5639609  -0.6416578 ]
 [ 0.5128391   0.20828098 -0.18587887]
 [ 0.39804256  0.21382582  0.00863415]
 [ 0.5175458   0.21059829 -0.24433091]
 [-0.6426642   0.6496494   0.632643  ]
 [ 0.59067523  0.53283644 -0.11620384]
 [ 0.21018624 -0.11227214  0.16085815]
 [-0.61708987  0.5211654   0.57554007]
 [ 0.342363    0.28888625 -0.17383581]
 [-0.5415174   0.21086365 -0.58172095]] 

B : (3,) 
 [0. 0. 0.] 

Y : (1, 3) 
 [[0.21429257 0.16108681 0.6746379 ]] 



In [7]:
## self

import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

w, b = tf.constant(2.), tf.constant(1.)
w_init, b_init = Constant(w), Constant(b)

X = tf.random.uniform(shape=(3, 3), minval=0, maxval=9, dtype=tf.int32)
dense = tf.keras.layers.Dense(units=5, 
                              activation="linear", 
                              kernel_initializer=w_init, 
                              bias_initializer=b_init)
Y = dense(X)

W, B = dense.get_weights() ## Bias도 뉴런의 수만큼 생성된다.

print(f"Input : {X.shape} \n {X.numpy()} \n")
print(f"Weight : {W.shape} \n {W} \n")
print(f"Bias : {B.shape} \n {B} \n")
print(f"Output : {Y.shape} \n {Y.numpy()}")

Input : (3, 3) 
 [[5 7 4]
 [6 2 4]
 [4 3 8]] 

Weight : (3, 5) 
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]] 

Bias : (5,) 
 [1. 1. 1. 1. 1.] 

Output : (3, 5) 
 [[33. 33. 33. 33. 33.]
 [25. 25. 25. 25. 25.]
 [31. 31. 31. 31. 31.]]


## Forward Propagation
<img src="https://drive.google.com/uc?export=download&id=1kiCuIlaI8OOJaJzSESGhbqtMCxKMzMzA">

- input x<sub>l<sub>i</sub></sub>만큼 weight vector의 차원이 동일하게 맞춰진다.
- l<sub>i</sub>개의 weight를 가진 뉴런들이 <sub>1</sub>개 존재하므로, weight matrix는 l<sub>i</sub> × l<sub>1</sub>
- x(row vector)와 weight matrix 간의 dot product(inner product)를 통해 l<sub>i</sub> × 1 의 row vector를 얻게된다.
- 마지막으로 bias vector(row form)을 더해주면 layer_1의 연산이 끝난 것이다.

In [ ]:
N, n_feature = 8, 10 ## batch-size : 8, row vectors : 10 // (8, 10) input matrix
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = tf.keras.layers.Dense(units=n_neuron, activation="sigmoid") ## 3 neurons // (10 x 3) weight matrix
## Column wise == neuron

Y = dense(X)

W, B = dense.get_weights()

print(f"X : {X.shape} \n {X.numpy()} \n")
print(f"W : {W.shape} \n {W} \n")
print(f"B : {B.shape} \n {B} \n")
print(f"Y : {Y.shape} \n {Y.numpy()} \n") ## Row wise == input matrix의 row(data sample)과 weight matrix의 column(neuron) 간 dot product

X : (8, 10) 
 [[ 0.86356735  0.34199923 -0.04937594  0.9168514   2.0846777  -0.21359067
  -0.5370583   0.09552217  0.7897584  -1.2188591 ]
 [-0.3305922   0.55810815  1.0076561   0.06520826 -0.6828096   1.5428512
   0.4369008   2.1800418   1.2655302  -0.10741881]
 [-0.280456   -0.5860013  -0.11978532 -0.19179282 -2.4775827  -1.2100868
   1.7028368  -0.08767257 -0.18099645 -0.06131132]
 [-1.7963477  -0.9407741  -0.07166364 -0.786007    0.8271763  -0.29297012
   0.54351187 -0.63952667 -0.13407816  0.6640327 ]
 [ 1.1123961  -1.77827    -1.2147692   0.12370616 -0.41512802  0.48415267
  -0.35735843 -0.29713038 -2.1594112  -0.5408446 ]
 [ 1.1393626   0.3490962  -0.03056625 -0.5924678  -0.3559421  -0.14887623
   0.10820436 -0.35138658  1.0900651  -0.1889676 ]
 [ 0.46844515  1.272012    0.10104561 -1.3986534   0.29258227  0.53944093
   0.21019259 -0.59052056 -0.50973344 -0.018357  ]
 [ 0.38321337 -0.47588986 -0.00548279 -0.44662064  0.2953757  -0.43118733
   0.12399973  0.10197753 -1.1070335  -

In [ ]:
X = tf.random.normal(shape=(16, 5)) ## 5차원 row vector가 16개가 한묶음
dense = tf.keras.layers.Dense(units=4, activation="sigmoid") ## 뉴런이 4개인 layer. 5 by 4 matrix.
Y = dense(X) ## 16 by 4

W, b = dense.get_weights()
print(f"X : {X.shape} \n {X.numpy()}")
print(f"W : {W.shape} \n {W}")
print(f"b : {b.shape} \n {b}")
print(f"Y : {Y.shape} \n {Y}")

X : (16, 5) 
 [[-1.2542684  -0.29523227  0.3044863   0.40145037 -0.55971   ]
 [-0.66338795  1.8652354   1.0352159   0.16756272  1.3720359 ]
 [ 0.35065296 -1.3674057  -0.7195325   0.43773213 -1.7857894 ]
 [ 1.4083174  -1.6047513  -1.5126861  -0.16746797 -0.33231178]
 [-2.0493379  -0.54980755 -0.8427084   1.3903923  -0.7814952 ]
 [ 0.29972228 -0.13862365  1.4724296  -0.87355083  0.43665645]
 [ 0.8137328  -1.5775731   0.80102754 -0.06934482 -0.40610322]
 [ 1.7241671   0.1391657  -0.62770087  0.40551665  0.4652951 ]
 [ 0.37758306 -0.3923751  -1.0472332  -0.8208615  -1.1105458 ]
 [-1.5060605  -0.5038025   0.14006555  0.41675258  0.5384123 ]
 [ 1.148592   -0.9473977   0.46976498 -0.68402284 -0.27519414]
 [ 0.91028273 -0.09760773  0.3327122   0.4382891   0.23806292]
 [-0.23569639  1.1383486   1.1384698  -1.0441151   1.9330343 ]
 [-1.9129155   2.267934   -1.6194302   1.476787   -1.0326943 ]
 [ 0.11850864  0.08111261  0.04322146  0.27080342 -0.93666047]
 [-0.32779893  1.4619396   1.5778675   0.

In [ ]:
## Manual
import numpy as np

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = tf.keras.layers.Dense(units=n_neuron, activation="sigmoid")
Y_tf = dense(X)

W, B = dense.get_weights()

## calculate with matrix multiplication.
Z = tf.linalg.matmul(X, W) + B
Y_man_mat_mul = 1 / (1 + tf.math.exp(-Z))

## calculate with dot product.
Y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
  x = X[x_idx] ## row 단위로 접근.

  for neuron_idx in range(n_neuron):
    w, b = W[:, neuron_idx], B[neuron_idx] ## W[:, neuron_idx] column 단위로 접근.
    z = tf.reduce_sum(x * w) + b
    a = 1 / (1 + np.exp(-z))
    Y_man_vec[x_idx, neuron_idx] = a


print(f"Y tensorflow : {Y_tf.shape}, \n {Y_tf.numpy()} \n")
print(f"Y man mat_mul : {Y_man_mat_mul.shape}, \n {Y_man_mat_mul} \n")
print(f"Y man vec : {Y_man_vec.shape} \n {Y_man_vec} \n")


Y tensorflow : (4, 3), 
 [[0.8620618  0.6017868  0.8499242 ]
 [0.46004727 0.8892391  0.8564313 ]
 [0.48217875 0.762668   0.66504467]
 [0.14955254 0.1649891  0.24311396]] 

Y man mat_mul : (4, 3), 
 [[0.8620618  0.6017868  0.8499242 ]
 [0.46004725 0.889239   0.85643125]
 [0.48217872 0.76266795 0.6650446 ]
 [0.14955254 0.1649891  0.24311395]] 

Y man vec : (4, 3) 
 [[0.86206178 0.60178682 0.84992421]
 [0.46004726 0.8892391  0.8564313 ]
 [0.48217873 0.76266795 0.66504461]
 [0.14955256 0.16498911 0.24311398]] 



## Add second Dense Layer
<img src="https://drive.google.com/uc?export=download&id=1ecTOm-jmKQfLrZxjxjI8wTKwrv1Ti7fy">
<img src="https://drive.google.com/uc?export=download&id=1ADkmcEuKtxsiQ4SLhRfsdXUj367bg9U7">
<img src="https://drive.google.com/uc?export=download&id=1-V5H-0v1bDhbeWojCpUa89147JMlpEhH">

이제 dense layer를 하나 추가한다. 전반적인 연산 과정은 이전과 동일하지만  
주목해야할 점은 
- layer_1의 output이 layer_2의 input으로 사용된다.
- layer_1의 output shape : 1 × l<sub>1</sub>
- weight의 수는 input의 차원과 동일해야하므로, l<sub>1</sub> × l<sub>2</sub>

## Generalize Dense Layer
일반화된 수식으로 앞에서 다룬 내용을 정리해보자.

<img src="https://drive.google.com/uc?export=download&id=1DLFeTMaQ0RfMydThYvto_eoQ5q_x52O0">
<img src="https://drive.google.com/uc?export=download&id=1VV73NLtIyYKUMzybk8bzJm3Rk1Bvn-jH">

- i-1번째 layer의 출력값이 i번째의 입력으로 사용된다.
- 만약 i-1번째 layer의 출력값 형태가 1 × l<sub>i-1</sub>라면
- i번째 layer의 weight matrix는 i<sub>i-1</sub> × i<sub>i</sub>
- 즉 weight vector의 shape은 i<sub>i-1</sub> × 1

## Minibatch in Dense Layers
minibatch는 row vector들을 쌓은 행렬이라고 lecture 1에서 다루었다.  
또한 minibatch가 되었다고 해서, layer의 parameter의 수나 값이 변하지 않는다. 
<img src="https://drive.google.com/uc?export=download&id=1v3roV_EASesuxSQY6uaKGVXgwP3OigR9"> 

그렇다면 dense layer로 minibatch를 입력했을 때의 연산과정을 살펴보자.
<img src="https://drive.google.com/uc?export=download&id=1BlokXqSS2wGRik0bUv5v6GqWf4TqozXs">

전체적인 연산과정은 동일하다.
- 입력이 행렬로 바뀌었으므로, row vector x<sup>1</sup>이 weight matrix를 column wise로 dot product를 수행.
- 그 결과가 Matrix A의 첫번째 row가 된다.
- 다음으로 row vector x<sup>2</sup>가 weight matrix를 column wise로 dot product.
- 결과 row vector가 Matrix A의 두번째 row가 된다.
- N번째까지 동일하게 연산이 진행된다.

### 출력값 행렬 분석

<img src="https://drive.google.com/uc?export=download&id=141jLWopFztKAOzOEiKwDYBlFwFig4bI9">

Matrix A의 
- row들은 minibatch인 X의 행렬을 row vector단위로 layer가 가진 각각의 뉴런들을 거쳐서 얻은 결과값들이다.(Batch된 data단위, batch-wise)
- column들은 minbatch X 행렬의 i번째 column이 layer의 i번째 뉴런을 거쳐서 얻은 결과값들이다.(i번째 뉴런 단위, neuron-wise)

In [ ]:
## Multiple Dense layers

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [3, 5]
dense1 = tf.keras.layers.Dense(units=n_neurons[0], activation="sigmoid") ## layer를 거쳐도 minibatch size N은 바뀌지 않는다!!!
dense2 = tf.keras.layers.Dense(units=n_neurons[1], activation="sigmoid") ## layer를 거쳐도 minibatch size N은 바뀌지 않는다!!!

A1 = dense1(X)
Y = dense2(A1)

W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print(f"X : {X.shape} \n {X.numpy()} \n")

print(f"W1 : {W1.shape} \n {W1} \n")
print(f"B2 : {B1.shape} \n {B1} \n")
print(f"A1 : {A1.shape} \n {A1.numpy()} \n")

print(f"W2 : {W2.shape} \n {W2} \n")
print(f"B2 : {B2.shape} \n {B2} \n")
print(f"Y : {Y.shape} \n {Y.numpy()} \n")

X : (4, 10) 
 [[-1.1527294   1.028705   -0.30607077 -2.5039365  -1.0834688   1.7216122
   1.4004226  -0.3131567   0.11873918  2.0624187 ]
 [ 0.25842085  1.8076994   1.2125925  -0.25394768 -0.9753505  -0.33679712
  -0.82873064 -1.0289067  -0.04862465  0.75584316]
 [ 2.4999115   0.41161326  1.0856723  -0.617261   -0.32245123  0.13356194
   1.1235652   0.5338114   0.9207963   0.04049225]
 [ 0.4263557  -0.9590861   0.5813131   0.3872085   1.7720155  -1.3388429
   0.23468076 -0.3905542  -1.9063684  -0.2379089 ]] 

W1 : (10, 3) 
 [[ 0.48086655 -0.06317729  0.07546592]
 [ 0.4748925   0.6446307  -0.11569577]
 [ 0.07855749  0.03108013  0.08240193]
 [ 0.3398018  -0.40620226 -0.27289188]
 [ 0.07079488  0.09826237 -0.62729937]
 [ 0.16344571  0.67326534 -0.52377284]
 [ 0.32270765  0.5499846   0.3095672 ]
 [-0.06496853 -0.58941895 -0.64709884]
 [ 0.515689    0.17054874  0.5042536 ]
 [-0.1958754  -0.04225695 -0.15172416]] 

B2 : (3,) 
 [0. 0. 0.] 

A1 : (4, 3) 
 [[0.3528678  0.97549534 0.64865315]
 [

In [ ]:
## dense layer with python list
N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
dense_layers = list()
for n_neuron in n_neurons:
  dense = tf.keras.layers.Dense(units=n_neuron, activation="relu")
  dense_layers.append(dense)

print(f"Input X : {X.shape}")
for dense_idx, dense in enumerate(dense_layers):
  # print(dense)
  X = dense(X)
  print(f"After {dense_idx+1} dense layer : {X.shape}")

print(f"Output X : {X.shape}")

Input X : (4, 10)
After 1 dense layer : (4, 10)
After 2 dense layer : (4, 20)
After 3 dense layer : (4, 30)
After 4 dense layer : (4, 40)
After 5 dense layer : (4, 50)
After 6 dense layer : (4, 60)
After 7 dense layer : (4, 70)
After 8 dense layer : (4, 80)
After 9 dense layer : (4, 90)
After 10 dense layer : (4, 100)
Output X : (4, 100)


In [ ]:
N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_copy = tf.identity(X)

n_neurons = [3, 4, 5]
dense_layers = list()
for n_neuron in n_neurons:
  dense = tf.keras.layers.Dense(units=n_neuron, activation="sigmoid")
  dense_layers.append(dense)

print(f"Input : {X.shape}")

W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  w, b = dense.get_weights()

  W.append(w), B.append(b)

print(f"Y tf : \n {X.numpy()}")


for layer_idx in range(len(n_neurons)):
  w, b = W[layer_idx], B[layer_idx]
  X_copy = tf.linalg.matmul(X_copy, w) + b
  X_copy = 1 / (1 + tf.math.exp(-X_copy))

print(f"Y man : \n {X_copy.numpy()}")

Input : (4, 10)
Y tf : 
 [[0.47295672 0.60801417 0.54474163 0.3138575  0.47409844]
 [0.4496807  0.59281564 0.55678976 0.31927904 0.47951674]
 [0.45077643 0.59325194 0.5529749  0.31480235 0.47498667]
 [0.44855917 0.5918597  0.5541313  0.31528392 0.47552872]]
Y man : 
 [[0.47295672 0.6080141  0.5447417  0.31385753 0.4740984 ]
 [0.4496807  0.59281564 0.55678976 0.31927904 0.4795167 ]
 [0.4507764  0.59325194 0.5529748  0.31480238 0.47498664]
 [0.44855917 0.59185964 0.5541313  0.31528395 0.47552872]]


In [ ]:
## input
X = tf.random.normal(shape=(4, 10))

In [ ]:
## Model Implemetation - Use Sequential

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=10, activation="sigmoid"))
model.add(tf.keras.layers.Dense(units=20, activation="sigmoid"))

Y = model(X)
print(Y.numpy())

[[0.5006219  0.46653876 0.5551453  0.40625468 0.34165624 0.38242137
  0.5382013  0.68218315 0.6575505  0.59405124 0.55194455 0.3578304
  0.3743886  0.40750426 0.4631241  0.578291   0.5455659  0.33900678
  0.52721584 0.6127003 ]
 [0.5000555  0.4665051  0.5552435  0.40685174 0.34211385 0.3825857
  0.5383901  0.68171555 0.65690327 0.59400547 0.55074584 0.3586409
  0.37442502 0.40746313 0.46323022 0.5779435  0.5458325  0.3391968
  0.52779263 0.6122682 ]
 [0.5000209  0.46660045 0.5552221  0.4067525  0.34196702 0.3825257
  0.5382395  0.6817353  0.6570728  0.5939487  0.55093724 0.35852605
  0.37445638 0.40753046 0.46315378 0.5780489  0.5457346  0.3389862
  0.5277787  0.6124163 ]
 [0.49996957 0.46659717 0.55523044 0.40680787 0.34201202 0.3825423
  0.5382554  0.6816917  0.6570127  0.5939449  0.5508252  0.35860315
  0.37445897 0.4075287  0.46316567 0.5780175  0.5457598  0.33900386
  0.52783346 0.61237395]]


In [ ]:
## Model Implemetation - Use Subclassing

class TestModel(tf.keras.models.Model):
    def __init__(self):
        super(TestModel, self).__init__()

        self.dense1 = tf.keras.layers.Dense(units=10, activation="sigmoid")
        self.dense2 = tf.keras.layers.Dense(units=20, activation="sigmoid")

    def call(self, x):
        x = self.dense1(x)
        x = self.dense2(x)

        return x


model = TestModel()
Y = model(X)
print(Y.numpy())

[[0.51289296 0.4934756  0.59600556 0.5134553  0.44572946 0.5321825
  0.4027883  0.6747661  0.4576317  0.530953   0.596469   0.6055598
  0.48547143 0.41525283 0.6070244  0.4413876  0.34306937 0.4689866
  0.46478942 0.63999546]
 [0.51300675 0.49314854 0.59508735 0.5136718  0.44491655 0.5323915
  0.4031409  0.67500603 0.457251   0.53114533 0.5966938  0.60581285
  0.48560315 0.41476655 0.60716593 0.44151503 0.34344307 0.46923524
  0.46459854 0.64026475]
 [0.51307017 0.49314946 0.5952974  0.51352394 0.4450474  0.53245234
  0.40303054 0.6750563  0.45720947 0.5310178  0.59670126 0.6057058
  0.48577186 0.4148413  0.607012   0.44156954 0.3434744  0.46908563
  0.46450776 0.6404088 ]
 [0.51307946 0.49311775 0.595209   0.513544   0.44497025 0.53247356
  0.40306446 0.67507946 0.4571716  0.53103757 0.59672207 0.6057292
  0.48578578 0.41479546 0.6070248  0.44158074 0.3435103  0.46910876
  0.46448848 0.6404331 ]]


In [ ]:
## layers in models
## Model Implemetation - Use Sequential

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=10, activation="sigmoid"))
model.add(tf.keras.layers.Dense(units=20, activation="sigmoid"))

Y = model(X)
# print(Y.numpy())

print(type(model.layers)) ## <class 'list'> 즉, model 내 layer들이 리스트로 담겨있다.
print(model.layers)
print(model.layers[0].get_weights())

<class 'list'>
[<keras.layers.core.dense.Dense object at 0x7f78f337d100>, <keras.layers.core.dense.Dense object at 0x7f78f34c1bb0>]
[array([[ 5.0868767e-01,  4.6924931e-01, -3.5472062e-01,  1.3442928e-01,
        -2.0060053e-01, -5.3231871e-01,  5.1297432e-01, -4.5654881e-01,
        -4.1657746e-02, -3.3682179e-01],
       [ 1.5235919e-01,  1.7234355e-01,  1.9654232e-01, -5.9407949e-04,
         1.9443113e-01, -9.8697543e-03, -6.2415129e-01,  5.8389360e-01,
         2.6347220e-01, -2.7995890e-01],
       [-3.6243680e-01, -1.6605747e-01,  3.8324589e-01, -5.0648177e-01,
         4.5956701e-01, -3.8383499e-01, -2.8901938e-01,  2.5075376e-01,
         5.7464534e-01,  4.0833086e-01],
       [-5.3965068e-01,  1.9459593e-01,  6.9273591e-02,  5.2275807e-01,
        -4.8871666e-01, -5.1995116e-01, -5.5051506e-01, -2.6331148e-01,
        -2.5872084e-01,  2.1657151e-01],
       [-2.2188789e-01, -3.0434105e-01, -5.0316393e-01,  1.5037340e-01,
         4.4962591e-01,  9.6127927e-02,  2.6454204e-01,

In [ ]:
## Trainable Variables in models
## Model Implemetation - Use Sequential

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=10, activation="sigmoid"))
model.add(tf.keras.layers.Dense(units=20, activation="sigmoid"))

Y = model(X)
# print(Y.numpy())

print(type(model.trainable_variables))
print(len(model.trainable_variables))

for train_variable in model.trainable_variables:
    print(train_variable.shape) ## model을 구성하는 Layer들이 가진 weight, bias들.

<class 'list'>
4
(5, 10)
(10,)
(10, 20)
(20,)
