## 1.Parametric Function
함수가 기본적으로 파라미터 θ를 포함하고 있다. 입력을 받으면 함수내 정의된 logic의 연산에 θ를 이용한다.

<img src="https://drive.google.com/uc?export=download&id=1Gj6ow44vICV_Ysuwp3R5EWzIUPWpflq1">

일반적인 함수는 정의된 logic대로 연산결과를 출력하지만, parametric function은 함수가 보유중인 파라미터를 추가적으로 이용한다.  
따라서 θ값이 변하면(다르면) 동일한 함수여도 다른 결과를 얻게 된다.

## 2.Tensor
텐서는 일반적으로 다차원 배열이나, 스칼라값도 가질 수 있다. 스칼라, 벡터, 행렬 그리고 그 이상의 고차원 배열들을 담는 그릇이자 하나의 단위가 텐서라고 이해하면 될 듯하다.

<img src="https://drive.google.com/uc?export=download&id=1YZ8xi6Cw3n6kVq3ucNb8CDpl_IZ5IfUH">

0차원 텐서에서 두 개의 실수간 덧셈, 곱셈을 기반으로 1차원, 2차원, 3차원 텐서에서의 연산으로 확장이 가능하며 새로운 연산을 정의할 수도 있다.

## 3.Dataset
통상적으로 한 개의 데이터는 row vector 형태로 다룬다.  
그리고 row vector 데이터들이 모여서(쌓여서) 하나의 데이터셋을 구성하게 된다.
<img src="https://drive.google.com/uc?export=download&id=1RAwlV3Aj-2Q6_vZRMXncKZzFnnGE88L_">

참고로 l<sub>i</sub>는 length of input. 즉 한 개의 데이터(1 row)의 길이를 의미한다.

## 3.Weighted Sum & Affine Transformation
<img src="https://drive.google.com/uc?export=download&id=1rtP6ZHbIhbKPrzUERmO2q1PAzgW13smW" width="480" height="640">

- weighted sum은 입력값 x에 함수가 보유중인 파라미터 w(weight)를 곱해준다. weight의 기능은 입력값 x가 z값에 얼마만큼의 영향을 주게될지 정해준다.
- Affine Transformation은 weighted sum에서 b(bias)라는 파라미터가 추가된 것.

이번에는 데이터 1개가 아니라 다수의 데이터에 대한 식을 알아보자.
<img src="https://drive.google.com/uc?export=download&id=174eUsZdhUgA3vUQ8hdALXt8RTxrkp68M">
<img src="https://drive.google.com/uc?export=download&id=1UmyX5aEypKLyRby17R9BURhKzepzld9d">

데이터의 수가 늘어나도 함수 자체의 연산은 동일하다.  
weight가 하는 역할은 입력값 x<sub>1</sub>, x<sub>2</sub>, x<sub>n</sub> 들 각각이 함수값 z에 미치는 영향력을 지정하는 것이다.

이때 중요한 사항은 입력 벡터 x<sub>l<sub>I</sub></sub>의 수와 가중치 벡터 w의 수가 같아야한다는 것이다.  
즉, 입력 벡터가 x<sub>1</sub>, x<sub>2</sub>, x<sub>3</sub> 이라면, 가중치 벡터의 형태는 w<sub>1</sub>, w<sub>2</sub>, w<sub>3</sub>가 되는 것이다. bias는 1개만 존재.

입력 데이터의 feature 수만큼, weight column이 생성된다.

In [ ]:
## 1개 데이터, 1개의 값에 대한 Affine Transform.
import tensorflow as tf

x = tf.constant([[10.]]) ## vector([10.])가 아니라 matrix([[10.]]) 형태임에 유의할 것. shape = (1, 1)

dense = tf.keras.layers.Dense(units=1, activation="linear") ## affine function

y = dense(x) ## output. forward propagation + parameter initialization(x값이 입력되는 시점에 weight, bias가 초기화 된다.)

W, B = dense.get_weights()

## Manual
y_manual = tf.linalg.matmul(x, W) + B

## print reuslt
print(f"x : {x.shape}, {x.numpy()}")
print(f"W : {W.shape}, {W}")
print(f"B : {B.shape}, {B}")
print(f"y : {y.shape}, {y.numpy()}")
print(f"y manual : {y_manual.shape}, {y_manual}")

x : (1, 1), [[10.]]
W : (1, 1), [[0.6688086]]
B : (1,), [0.]
y : (1, 1), [[6.6880856]]
y manual : (1, 1), [[6.6880856]]


In [2]:
## self ##
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.constant([[1., 4., 7.]]) ## (1, 3) row vector

dense = Dense(units=1, activation="linear") ## (3, 1) column vector
y = dense(x) ## 1 by 1

W, b = dense.get_weights()
print(f"input : {x.shape} \n {x} \n")
print(f"Weight : {W.shape} \n {W} \n")
print(f"bias : {b.shape} \n {b} \n")
print(f"output : {y.shape} \n {y}")

input : (1, 3) 
 [[1. 4. 7.]] 

Weight : (3, 1) 
 [[-0.21766675]
 [-1.0486946 ]
 [-0.42008948]] 

bias : (1,) 
 [0.] 

output : (1, 1) 
 [[-7.353071]]


In [ ]:
## weight, bias initializer
from tensorflow.keras.initializers import Constant

w, b = tf.constant(10.), tf.constant(20.)
## Tensor를 만드는게 아니라 Layer의 parameter를 초기화 시키는 object를 만든 것.
w_init, b_init = Constant(w), Constant(b)
print(w_init, b_init)

dense = tf.keras.layers.Dense(units=1, 
                              activation="linear", 
                              kernel_initializer=w_init, 
                              bias_initializer=b_init)
y = dense(x)
W, B = dense.get_weights()

print(f"y. : {y.shape}, {y}")
print(f"W : {W.shape}, {W}")
print(f"B : {B.shape}, {B}")

<keras.initializers.initializers_v2.Constant object at 0x7f4ee381b310> <keras.initializers.initializers_v2.Constant object at 0x7f4ee37b5bb0>
y. : (1, 1), [[140.]]
W : (3, 1), [[10.]
 [10.]
 [10.]]
B : (1,), [20.]


In [ ]:
## 한 개의 row vector data. 10개의 feature.
x = tf.random.uniform(shape=(1, 10), minval=0, maxval=10)

dense = tf.keras.layers.Dense(units=1)
y = dense(x)
W, B = dense.get_weights()

y_manual = tf.linalg.matmul(x, W) + B

## print reuslt
print(f"x : {x.shape} \n {x.numpy()}") ## row vector
print(f"W : {W.shape} \n {W}") ## column vector
print(f"B : {B.shape} \n {B}")
print(f"y : {y.shape} \n {y.numpy()}")
print(f"y manual : {y_manual.shape}, {y_manual}")

x : (1, 10) 
 [[2.7111328  4.7499695  6.7036486  3.884046   2.8344262  4.377949
  0.80842614 0.01494527 6.9357643  0.3285551 ]]
W : (10, 1) 
 [[-0.11228108]
 [ 0.13207024]
 [ 0.08529449]
 [ 0.05172127]
 [ 0.48589462]
 [-0.01613331]
 [-0.7165279 ]
 [ 0.5260306 ]
 [ 0.08768076]
 [ 0.41819018]]
B : (1,) 
 [0.]
y : (1, 1) 
 [[2.5763278]]
y manual : (1, 1), [[2.5763278]]


## 4.Activation Function

Affine Transformation을 거친 이후에, Activation function을 적용하게 된다.  
이는 activation function에 입력된 값이 적용한 활성화 함수의 연산에 따라 결과값이 결정되는 형태다.
<img src="https://drive.google.com/uc?export=download&id=1xP6YiARnabEQj2xz-rOXOYgPXl3JWBXq">
<img src="https://drive.google.com/uc?export=download&id=12Wn0dTJzxkYh1G3Y232E8XaZ2NtKAmXn">

In [ ]:
## input & Activation func.

x = tf.random.normal(shape=(1, 5))

sigmoid = tf.keras.layers.Activation("sigmoid")
tanh = tf.keras.layers.Activation("tanh")
relu = tf.keras.layers.Activation("relu")

y_sigmoid = sigmoid(x)
y_tanh = tanh(x)
y_relu = relu(x)

print(f"x : {x.shape}, {x.numpy()} \n")
print(f"Sigmoid : {y_sigmoid.shape}, {y_sigmoid.numpy()}")
print(f"Tanh : {y_tanh.shape}, {y_tanh.numpy()}")
print(f"ReLU : {y_relu.shape}, {y_relu.numpy()} \n")

y_sigmoid_man = 1 / (1 + tf.math.exp(-x))
y_tanh_man = (tf.exp(x) - tf.exp(-x)) / (tf.exp(x) + tf.exp(-x))
y_relu_man = tf.math.maximum(x, 0)

print(f"Sigmoid manual : {y_sigmoid_man.shape}, {y_sigmoid_man.numpy()}")
print(f"Tanh manual : {y_tanh_man.shape}, {y_tanh_man.numpy()}")
print(f"ReLU manual : {y_relu_man.shape}, {y_relu_man.numpy()}")

x : (1, 5), [[ 0.47400722  0.68043196  0.26013425 -0.27689335  1.4365736 ]] 

Sigmoid : (1, 5), [[0.61633176 0.6638351  0.5646693  0.43121555 0.8079235 ]]
Tanh : (1, 5), [[ 0.44143143  0.59180015  0.2544211  -0.27002737  0.89300585]]
ReLU : (1, 5), [[0.47400722 0.68043196 0.26013425 0.         1.4365736 ]] 

Sigmoid manual : (1, 5), [[0.61633176 0.6638351  0.5646693  0.43121555 0.8079235 ]]
Tanh manual : (1, 5), [[ 0.44143137  0.59180015  0.25442111 -0.27002743  0.89300585]]
ReLU manual : (1, 5), [[0.47400722 0.68043196 0.26013425 0.         1.4365736 ]]


In [ ]:
## Affine Transform with Activation Func.
x = tf.random.normal(shape=(1, 5))

dense_sigmoid = tf.keras.layers.Dense(units=1, activation="sigmoid")
y_sigmoid = dense_sigmoid(x)

dense_tanh = tf.keras.layers.Dense(units=1, activation="tanh")
y_tanh = dense_tanh(x)

dense_relu = tf.keras.layers.Dense(units=1, activation="relu")
y_relu = dense_relu(x)

print(f"dense sigomid : {y_sigmoid.shape}, {y_sigmoid.numpy()}")
print(f"dense tanh : {y_tanh.shape}, {y_tanh.numpy()}")
print(f"dense  relu : {y_relu.shape}, {y_relu.numpy()} \n")

W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1 / (1 + tf.math.exp(-z))
print(f"dense sigmoid manual : {a.shape}, {a}")

dense sigomid : (1, 1), [[0.60975546]]
dense tanh : (1, 1), [[0.9439984]]
dense  relu : (1, 1), [[0.6568093]] 

dense sigmoid manual : (1, 1), [[0.60975546]]


In [ ]:
## self ##

x = tf.random.normal(shape=(1, 10)) ## 1 by 10.

dense_sigmoid = Dense(units=1, activation="sigmoid") ## weights : 10 by 1, bias : 1 activation : sigmoid
y = dense_sigmoid(x)
W, b = dense_sigmoid.get_weights()
print(f"W : {W.shape} \n {W}")
print(f"b : {b.shape} \n {b}")
print(f"y tf : {y.shape} \n {y.numpy()}")

y_man = tf.linalg.matmul(x, W) + b ## Affine Transform.
y_man = 1 / (1 + tf.math.exp(-y_man)) ## Sigmoid func.
print(f"y_man : {y_man.shape} \n {y}")

W : (10, 1) 
 [[-0.31999266]
 [-0.6403414 ]
 [ 0.38386375]
 [-0.5370061 ]
 [ 0.25103617]
 [-0.5355664 ]
 [ 0.31952423]
 [-0.26529628]
 [ 0.7364002 ]
 [-0.04152161]]
b : (1,) 
 [0.]
y tf : (1, 1) 
 [[0.5928964]]
y_man : (1, 1) 
 [[0.5928964]]


## 5.Mini-Batch

mini batch는 데이터를 하나의 묶음으로 입력하는 것을 의미한다. 예를 들어 batch-size가 32라면 1개의 데이터 묶음 속에 32개의 데이터가 들어가 있다.  
데이터 묶음 속 각각의 데이터가 Affine transform, Activation function을 거치게 되는데 이때 함수들이 가지고 있는 weight, bias는 값이 변하지 않음에 유의할 것.

<img src="https://drive.google.com/uc?export=download&id=10FPGwD4wM-62ziN30kdVB4VaOaxpfs_e">
<img src="https://drive.google.com/uc?export=download&id=14sdWrA81UoT3XViGCA9WMbplrf9FdbD6">

In [5]:
## Affine Trans + Activation func with Mini-batch
N, n_feature = 3, 5
x = tf.random.normal(shape=(N, n_feature))

dense = tf.keras.layers.Dense(units=1, activation="sigmoid")
y = dense(x)

W, B = dense.get_weights() ## Mini-batch size는 weight, bias에 영향을 끼치지 않는다!!!

print(f"x : {x.shape} \n {x.numpy()}")
print(f"W : {W.shape} \n {W}")
print(f"B : {B.shape} \n {B}")
print(f"y : {y.shape} \n {y.numpy()}")

x : (3, 5) 
 [[ 0.454314   -0.6143074  -0.19492248 -0.22771174 -1.7071912 ]
 [-0.1889215   0.80534655 -2.092378   -1.4967377  -0.6269125 ]
 [-1.3200445  -0.09606645 -0.9125424   0.7046709   0.56615615]]
W : (5, 1) 
 [[-0.8701072 ]
 [-0.9129729 ]
 [ 0.10068583]
 [-0.88756704]
 [-0.8946471 ]]
B : (1,) 
 [0.]
y : (3, 1) 
 [[0.8670774]
 [0.7517131]
 [0.5031133]]


In [7]:
y_man = tf.linalg.matmul(x, W) + B
y_man = 1 / (1 + tf.math.exp(-y_man))

print(f"y tensorflow: {y.shape} \n {y.numpy()} \n")
print(f"y manual : {y_man.shape} \n{y_man.numpy()}")

y tensorflow: (3, 1) 
 [[0.8670774]
 [0.7517131]
 [0.5031133]] 

y manual : (3, 1) 
[[0.8670774]
 [0.7517131]
 [0.5031133]]


In [ ]:
## self ##
X = tf.random.normal(shape=(10, 5)) ## batch-size = 10, feature in row wise = 5

dense = Dense(units=1, activation=("sigmoid"))
Y = dense(X)

W, b = dense.get_weights()
print(f"X : {X.shape} \n {X.numpy()}")
print(f"W : {W.shape} \n {W}")
print(f"b : {b.shape} \n {b}")
print(f"Y : {Y.shape} \n {Y.numpy()}")

Z = tf.linalg.matmul(X, W) + b
A = 1 / (1 + tf.math.exp(-Z))
print(f"A : {A.shape} \n {A}")

X : (10, 5) 
 [[ 0.05838945 -0.01629276  0.24191903  0.49484608  0.8030093 ]
 [ 2.4908857   0.76183707  2.1102815   0.9737939  -1.1018577 ]
 [-0.5412256  -0.04079812 -1.490813   -0.7238365  -0.29986432]
 [-0.76648015  0.50365984  0.02132273  1.4990809   0.80910254]
 [-0.7634293   0.67730844 -0.46383393 -1.389235    2.7689056 ]
 [-1.2981669  -1.6906124   0.4484961   0.9054918   1.177951  ]
 [ 0.03938768 -0.6596372  -1.0927767   0.40590832 -0.12904261]
 [ 0.04981457  2.2720761  -1.2451718  -0.367394    0.46084523]
 [ 0.7832895  -0.02164987 -1.1234018   1.6135793  -0.76239365]
 [ 2.1102645   0.04436247  0.43940756  0.4966496   1.9832909 ]]
W : (5, 1) 
 [[ 0.32691073]
 [ 0.38050508]
 [ 0.99193215]
 [-0.9726291 ]
 [ 0.00578141]]
b : (1,) 
 [0.]
Y : (10, 1) 
 [[0.44428155]
 [0.9041253 ]
 [0.27508962]
 [0.18374968]
 [0.7140779 ]
 [0.18291956]
 [0.15217751]
 [0.5014245 ]
 [0.0801484 ]
 [0.6617318 ]]
A : (10, 1) 
 [[0.44428155]
 [0.9041253 ]
 [0.27508962]
 [0.18374968]
 [0.7140779 ]
 [0.1829195